site_name: Apuntes MCR
nav:
  - Inicio: index.md
  - Introducción: intro/index.md
  - Biblia: 
    - Inicio: biblia/index.md
    - Apuntes: biblia/apuntes/blia.md
    - Materiales: biblia/materiales/
  - Cristianismo: 
    - Intro: cristianismo/index.md
    - Los orígenes del cristianismo: cristianismo/apuntes/t1.md
    - El cristianismo en los siglos II y III: cristianismo/apuntes/t2.md
    - El cristianismo de Estado: cristianismo/apuntes/t3.md
    - Controversias y herejías: cristianismo/apuntes/t4.md
    - La nueva sociedad cristiana: cristianismo/apuntes/t5.md
    - Concilio Vaticano II: cristianismo/apuntes/vaticano2.md
  - Judaísmo:
    - Intro: judaismo/intro.md
    - Judaísmo antiguo: judaismo/apuntes/t1
    - Judaísmo helenístico: 
        - Inicio: judaismo/apuntes/t2/index.md
        - Helenismo, hasidismo y Qumrán: judaismo/apuntes/t2/t2_1.md
        - Romanización y judeocristianismo: judaismo/apuntes/t2/t2_2.md
        - Rabinismo, Tanaj y Talmud: judaismo/apuntes/t2/t2_3.md
    - Judaísmo medieval: judaismo/apuntes/t3
    - Judaísmo moderno: judaismo/apuntes/t4
    - Judaísmo contemporáneo: judaismo/apuntes/t5
  - Islam:
    - Inicio: islam/index.md
    - Apuntes: islam/apuntes/
    - Materiales: islam/materiales/
  - Americanas:
    - Intro: americanas/index.md
    - Apuntes: americanas/apuntes/amcas.md
    - Materiales: americanas/materiales/
theme:
  language: gl
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'yellow'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'    
  font:
    text: Roboto
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moronbandin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moronbandin